# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Capella87.FixNormalization
PackageVersion: 0.2.3
InstallerType: zip
NestedInstallerType: portable
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: fnorm.exe
  InstallerUrl: https://github.com/Capella87/FixNormalization/releases/download/v0.2.3/fnorm-v0.2.3-win-x64.zip
  InstallerSha256: cdf59a62c5c9e603e168d8b2259abe8394b258935017824071426c4d41457f21
  Commands:
    - fnorm
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
        MinimumVersion: 10.0.0
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: fnorm.exe
  InstallerUrl: https://github.com/Capella87/FixNormalization/releases/download/v0.2.3/fnorm-v0.2.3-win-arm64.zip
  InstallerSha256: e8ccf2985c139b386f31b0ba94269f8cb4d5ee800a120a9d5cda7d504fb94d37
  Commands:
    - fnorm
  Dependencies:
    PackageDependencies:
      - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
        MinimumVersion: 10.0.0
ManifestType: installer
ManifestVersion: 1.12.0
