name: .NET deployment

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        rid: [ "win-x64", "win-arm64" ]
    runs-on: windows-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: false

      - name: restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build -c Release --no-restore

      - name: Publish
        run: |
          dotnet publish ./src/FixNormalization -c Release -o ./pub/${{ matrix.rid }} -r ${{ matrix.rid }} --no-self-contained -v normal

      - name: Test projects
        run: dotnet test --verbosity normal

      - name: Set Short SHA name to github.sha
        run: |
          sa=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SIX_SHA=$sa" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fnorm-build-${{ env.COMMIT_SHORT_SIX_SHA }}-${{ matrix.rid }}
          path: ./pub/${{ matrix.rid }}
          compression-level: 6
          if-no-files-found: warn
          retention-days: 10
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            fnorm-build-${{ env.COMMIT_SHORT_SIX_SHA }}-${{ matrix.rid }}

