name: .NET build and test

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test projects
        run: dotnet test --verbosity detailed


