name: .NET deployment

on:
  push:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: false

      - name: restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build -c Release --no-restore

      - name: Test projects
        run: dotnet test --verbosity normal

