name: .NET deployment

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build -c Release --no-restore

      - name: Publish
        run: |
          dotnet publish ./src/FixNormalization -c Release -o ./pub/win/amd64 -r win-x64 --no-self-contained -v normal
          dotnet publish ./src/FixNormalization -c Release -o ./pub/win/aarch64 -r win-arm64 --no-self-contained -v normal

      - name: Test projects
        run: dotnet test --verbosity normal

