name: .NET deployment

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        rid: [ "win-x64", "win-arm64" ]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build -c Release --no-restore

      - name: Publish
        run: |
          dotnet publish ./src/FixNormalization -c Release -o ./pub/${{ matrix.rid }} -r ${{ matrix.rid }} --no-self-contained -v normal

      - name: Test projects
        run: dotnet test --verbosity normal

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fnorm-${{ matrix.rid }}
          path: ./pub/${{ matrix.rid }}
          compression-level: 6
          if-no-files-found: warn
          retention-days: 10
